In [1]:
import pandas as pd
import yfinance as yf

def fetch_stocks_data(name, start_date, end_date):
    stock_data = yf.download(name, start_date, end_date)
    return stock_data

stock_data = fetch_stocks_data("AAPL","2023-01-01","2024-01-01")
stock_data

[*********************100%%**********************]  1 of 1 completed

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2023-01-03,130.279999,130.899994,124.169998,125.070000,124.374802,112117500
2023-01-04,126.889999,128.660004,125.080002,126.360001,125.657639,89113600
2023-01-05,127.129997,127.769997,124.760002,125.019997,124.325081,80962700
2023-01-06,126.010002,130.289993,124.889999,129.619995,128.899506,87754700
2023-01-09,130.470001,133.410004,129.889999,130.149994,129.426544,70790800
...,...,...,...,...,...,...
2023-12-22,195.179993,195.410004,192.970001,193.600006,193.600006,37122800
2023-12-26,193.610001,193.889999,192.830002,193.050003,193.050003,28919300
2023-12-27,192.490005,193.500000,191.089996,193.149994,193.149994,48087700
2023-12-28,194.139999,194.660004,193.169998,193.580002,193.580002,34049900
2023-12-29,193.899994,194.399994,191.729996,192.529999,192.529999,42628800

In [2]:
correlation=stock_data.corr()
correlation

               Open      High       Low     Close  Adj Close    Volume
Open       1.000000  0.997686  0.997888  0.994666   0.994693 -0.323980
High       0.997686  1.000000  0.997941  0.997657   0.997623 -0.299925
Low        0.997888  0.997941  1.000000  0.998021   0.997977 -0.335973
Close      0.994666  0.997657  0.998021  1.000000   0.999948 -0.320462
Adj Close  0.994693  0.997623  0.997977  0.999948   1.000000 -0.321075
Volume    -0.323980 -0.299925 -0.335973 -0.320462  -0.321075  1.000000

In [3]:
stock_data.drop(['Volume'], axis=1)

                  Open        High         Low       Close   Adj Close
Date
2023-01-03  130.279999  130.899994  124.169998  125.070000  124.374802
2023-01-04  126.889999  128.660004  125.080002  126.360001  125.657639
2023-01-05  127.129997  127.769997  124.760002  125.019997  124.325081
2023-01-06  126.010002  130.289993  124.889999  129.619995  128.899506
2023-01-09  130.470001  133.410004  129.889999  130.149994  129.426544
...                ...         ...         ...         ...         ...
2023-12-22  195.179993  195.410004  192.970001  193.600006  193.600006
2023-12-26  193.610001  193.889999  192.830002  193.050003  193.050003
2023-12-27  192.490005  193.500000  191.089996  193.149994  193.149994
2023-12-28  194.139999  194.660004  193.169998  193.580002  193.580002
2023-12-29  193.899994  194.399994  191.729996  192.529999  192.529999

[250 rows x 5 columns]

In [4]:
stock_data

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2023-01-03,130.279999,130.899994,124.169998,125.070000,124.374802,112117500
2023-01-04,126.889999,128.660004,125.080002,126.360001,125.657639,89113600
2023-01-05,127.129997,127.769997,124.760002,125.019997,124.325081,80962700
2023-01-06,126.010002,130.289993,124.889999,129.619995,128.899506,87754700
2023-01-09,130.470001,133.410004,129.889999,130.149994,129.426544,70790800
...,...,...,...,...,...,...
2023-12-22,195.179993,195.410004,192.970001,193.600006,193.600006,37122800
2023-12-26,193.610001,193.889999,192.830002,193.050003,193.050003,28919300
2023-12-27,192.490005,193.500000,191.089996,193.149994,193.149994,48087700
2023-12-28,194.139999,194.660004,193.169998,193.580002,193.580002,34049900
2023-12-29,193.899994,194.399994,191.729996,192.529999,192.529999,42628800

In [5]:
#So let's take the first 4 columns as input and drop the last column-Adj Close.

X=stock_data.drop(['Adj Close'],axis=1)
X

                  Open        High         Low       Close     Volume
Date
2023-01-03  130.279999  130.899994  124.169998  125.070000  112117500
2023-01-04  126.889999  128.660004  125.080002  126.360001   89113600
2023-01-05  127.129997  127.769997  124.760002  125.019997   80962700
2023-01-06  126.010002  130.289993  124.889999  129.619995   87754700
2023-01-09  130.470001  133.410004  129.889999  130.149994   70790800
...                ...         ...         ...         ...        ...
2023-12-22  195.179993  195.410004  192.970001  193.600006   37122800
2023-12-26  193.610001  193.889999  192.830002  193.050003   28919300
2023-12-27  192.490005  193.500000  191.089996  193.149994   48087700
2023-12-28  194.139999  194.660004  193.169998  193.580002   34049900
2023-12-29  193.899994  194.399994  191.729996  192.529999   42628800

[250 rows x 5 columns]

In [6]:
Y=stock_data['Adj Close']     #taking Y as Output as Adj Close
Y

Date
2023-01-03    124.374802
2023-01-04    125.657639
2023-01-05    124.325081
2023-01-06    128.899506
2023-01-09    129.426544
                 ...
2023-12-22    193.600006
2023-12-26    193.050003
2023-12-27    193.149994
2023-12-28    193.580002
2023-12-29    192.529999
Name: Adj Close, Length: 250, dtype: float64

In [7]:
from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test = train_test_split(X,Y, test_size=0.2,random_state=42)
X_train

                  Open        High         Low       Close    Volume
Date
2023-07-14  190.229996  191.179993  189.630005  190.690002  41573900
2023-11-24  190.869995  190.899994  189.250000  189.970001  24048300
2023-12-13  195.089996  198.000000  194.850006  197.960007  70404200
2023-06-26  186.830002  188.050003  185.229996  185.270004  48088700
2023-07-20  195.089996  196.470001  192.500000  193.130005  59581200
...                ...         ...         ...         ...       ...
2023-06-06  179.970001  180.119995  177.429993  179.210007  64848400
2023-01-24  140.309998  143.160004  140.300003  142.529999  66435100
2023-05-16  171.990005  173.139999  171.800003  172.070007  42110300
2023-09-20  179.259995  179.699997  175.399994  175.490005  58436200
2023-05-31  177.330002  179.350006  176.759995  177.250000  99625300

[200 rows x 5 columns]

In [8]:
from IPython.display import display_html
display(X_train)
display(X_test)
display(Y_train)
display(Y_test)

                  Open        High         Low       Close    Volume
Date
2023-07-14  190.229996  191.179993  189.630005  190.690002  41573900
2023-11-24  190.869995  190.899994  189.250000  189.970001  24048300
2023-12-13  195.089996  198.000000  194.850006  197.960007  70404200
2023-06-26  186.830002  188.050003  185.229996  185.270004  48088700
2023-07-20  195.089996  196.470001  192.500000  193.130005  59581200
...                ...         ...         ...         ...       ...
2023-06-06  179.970001  180.119995  177.429993  179.210007  64848400
2023-01-24  140.309998  143.160004  140.300003  142.529999  66435100
2023-05-16  171.990005  173.139999  171.800003  172.070007  42110300
2023-09-20  179.259995  179.699997  175.399994  175.490005  58436200
2023-05-31  177.330002  179.350006  176.759995  177.250000  99625300

[200 rows x 5 columns]

                  Open        High         Low       Close     Volume
Date
2023-07-28  194.669998  196.630005  194.139999  195.830002   48291400
2023-01-11  131.250000  133.509995  130.460007  133.490005   69458900
2023-05-23  173.130005  173.380005  171.279999  171.559998   50747300
2023-03-30  161.529999  162.470001  161.270004  162.360001   49501700
2023-06-14  183.369995  184.389999  182.020004  183.949997   57462900
2023-09-22  174.669998  177.080002  174.050003  174.789993   56725400
2023-10-16  176.750000  179.080002  176.509995  178.720001   52517000
2023-09-27  172.619995  173.039993  169.050003  170.429993   66921800
2023-01-17  134.830002  137.289993  134.130005  135.940002   63646600
2023-06-02  181.029999  181.779999  179.259995  180.949997   61945900
2023-10-19  176.039993  177.839996  175.190002  175.460007   59302900
2023-11-10  183.970001  186.570007  183.529999  186.399994   66133400
2023-12-11  193.110001  193.490005  191.419998  193.179993   60943700
2023-12-15  197.529999  198.399994  197.000000  197.570007  128256700
2023-04-11  162.350006  162.360001  160.509995  160.800003   47644200
2023-11-22  191.490005  192.929993  190.830002  191.309998   39617700
2023-10-11  178.199997  179.850006  177.600006  179.800003   47551100
2023-01-25  140.889999  142.429993  138.809998  141.860001   65799300
2023-09-18  176.479996  179.380005  176.169998  177.970001   67257600
2023-02-07  150.639999  155.229996  150.639999  154.649994   83322600
2023-12-27  192.490005  193.500000  191.089996  193.149994   48087700
2023-01-31  142.699997  144.339996  142.279999  144.289993   65874500
2023-06-16  186.729996  186.990005  184.270004  184.919998  101235600
2023-04-12  161.220001  162.059998  159.779999  160.100006   50133100
2023-09-15  176.479996  176.500000  173.820007  175.009995  109205100
2023-03-09  153.559998  154.539993  150.229996  150.589996   53833600
2023-03-23  158.830002  161.550003  157.679993  158.929993   67622100
2023-01-18  136.820007  138.610001  135.029999  135.210007   69672800
2023-02-15  153.110001  155.500000  152.880005  155.330002   65573800
2023-06-27  185.889999  188.389999  185.669998  188.059998   50730800
2023-10-20  175.309998  175.419998  172.639999  172.880005   64189300
2023-02-21  150.199997  151.300003  148.410004  148.479996   58867200
2023-07-27  196.020004  197.199997  192.550003  193.220001   47460200
2023-11-15  187.850006  189.500000  187.779999  188.009995   53790500
2023-02-08  153.880005  154.580002  151.169998  151.919998   64120100
2023-06-13  182.800003  184.149994  182.440002  183.309998   54929100
2023-01-30  144.960007  145.550003  142.850006  143.000000   64015300
2023-10-13  181.419998  181.929993  178.139999  178.850006   51427100
2023-09-21  174.550003  176.300003  173.860001  173.929993   63047900
2023-08-22  177.059998  177.679993  176.250000  177.229996   42084200
2023-06-23  185.550003  187.559998  185.009995  186.679993   53079300
2023-05-22  173.979996  174.710007  173.449997  174.199997   43570900
2023-06-08  177.899994  180.839996  177.460007  180.570007   50214900
2023-09-28  169.339996  172.029999  167.619995  170.690002   56294400
2023-11-20  189.889999  191.910004  189.880005  191.449997   46505100
2023-01-26  143.169998  144.250000  141.899994  143.960007   54105100
2023-08-03  191.570007  192.369995  190.690002  191.169998   61235200
2023-04-13  161.630005  165.800003  161.419998  165.559998   68445600
2023-09-12  179.490005  180.130005  174.820007  176.300003   90370200
2023-02-28  147.050003  149.080002  146.830002  147.410004   50547000

Date
2023-07-14    190.182297
2023-11-24    189.970001
2023-12-13    197.960007
2023-06-26    184.776718
2023-07-20    192.615799
                 ...
2023-06-06    178.732864
2023-01-24    141.737747
2023-05-16    171.611877
2023-09-20    175.259109
2023-05-31    176.778076
Name: Adj Close, Length: 200, dtype: float64

Date
2023-07-28    195.308609
2023-01-11    132.748001
2023-05-23    171.103226
2023-03-30    161.704041
2023-06-14    183.460236
2023-09-22    174.560013
2023-10-16    178.484863
2023-09-27    170.205750
2023-01-17    135.184387
2023-06-02    180.468216
2023-10-19    175.229156
2023-11-10    186.399994
2023-12-11    193.179993
2023-12-15    197.570007
2023-04-11    160.150360
2023-11-22    191.309998
2023-10-11    179.563431
2023-01-25    141.071487
2023-09-18    177.735840
2023-02-07    153.790359
2023-12-27    193.149994
2023-01-31    143.487961
2023-06-16    184.427643
2023-04-12    159.453201
2023-09-15    174.779724
2023-03-09    149.981598
2023-03-23    158.287903
2023-01-18    134.458450
2023-02-15    154.702454
2023-06-27    187.559280
2023-10-20    172.652542
2023-02-21    147.880127
2023-07-27    192.705551
2023-11-15    188.009995
2023-02-08    151.075546
2023-06-13    182.821930
2023-01-30    142.205154
2023-10-13    178.614685
2023-09-21    173.701157
2023-08-22    176.996811
2023-06-23    186.182953
2023-05-22    173.736191
2023-06-08    180.089233
2023-09-28    170.465424
2023-11-20    191.449997
2023-01-26    143.159821
2023-08-03    190.661011
2023-04-13    164.891113
2023-09-12    176.068039
2023-02-28    146.814453
Name: Adj Close, dtype: float64

In [9]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)    #fit_transform() method in StandardScaler is used to scale data so that 
                                     #it has a mean of 0 and a standard deviation of 1.
X_train

array([[ 1.01070434e+00,  9.88666746e-01,  1.04981845e+00,
         1.03213899e+00, -9.52004724e-01],
       [ 1.04758471e+00,  9.72252636e-01,  1.02791273e+00,
         9.90060656e-01, -1.92594915e+00],
       [ 1.29076496e+00,  1.38846974e+00,  1.35073007e+00,
         1.45701281e+00,  6.50172091e-01],
       [ 8.14777542e-01,  8.05180253e-01,  7.96175995e-01,
         7.15383285e-01, -5.89959878e-01],
       [ 1.29076496e+00,  1.29877804e+00,  1.21526188e+00,
         1.17473769e+00,  4.87090583e-02],
       [-6.49490015e-01, -7.20166447e-01, -6.53617831e-01,
        -6.42809858e-01, -6.10621798e-01],
       [ 7.56575968e-01,  6.86763406e-01,  7.37377819e-01,
         6.87915458e-01, -8.37880684e-01],
       [ 3.56653932e-01,  3.02788622e-01,  3.24633023e-01,
         2.58366167e-01, -8.38152990e-01],
       [ 8.98334534e-01,  9.18320432e-01,  9.33373499e-01,
         9.74281058e-01, -7.46046843e-01],
       [ 9.88230382e-01,  9.38252618e-01,  9.66808222e-01,
         9.88891566e-01, -5.50742244e-01],
       [ 1.25388459e+00,  1.19853389e+00,  1.19278001e+00,
         1.12739979e+00, -9.78913012e-01],
       [ 2.56385013e-01,  1.87303058e-01,  1.18836767e-01,
         5.67413354e-02,  4.08914449e-01],
       [ 6.36714545e-01,  7.46558176e-01,  7.06248545e-01,
         8.16487750e-01, -4.14539181e-01],
       [-4.49528997e-01, -4.26470162e-01, -4.09775955e-01,
        -4.23068139e-01,  1.25209082e+00],
       [ 1.08792336e+00,  1.09418666e+00,  1.10688732e+00,
         1.06954186e+00, -6.54890989e-01],
       [ 9.68061938e-01,  9.14803251e-01,  9.71996141e-01,
         9.60255541e-01, -7.20894652e-01],
       [ 1.29595105e+00,  1.23663878e+00,  1.24235551e+00,
         1.20220552e+00, -1.19936425e+00],
       [ 5.07632810e-01,  4.63999334e-01,  5.31005421e-01,
         4.63498270e-01, -5.46502049e-01],
       [ 4.25228576e-01,  3.50859154e-01,  3.41349945e-01,
         3.69990662e-01,  1.38038628e-02],
       [ 1.20663202e+00,  1.21260351e+00,  1.27809569e+00,
         1.24136157e+00, -6.23914781e-01],
       [-3.97089459e-01, -3.60812827e-01, -3.38871754e-01,
        -3.15534122e-01, -6.10438408e-01],
       [ 1.37100409e-01,  1.06405200e-01,  1.33825262e-01,
         1.64274460e-01, -6.88701403e-01],
       [ 6.75323614e-01,  6.90867381e-01,  7.48906822e-01,
         7.00187786e-01, -4.94908380e-01],
       [-4.40308684e-01, -4.61056973e-01, -3.99399237e-01,
        -4.68067861e-01, -2.04177888e-02],
       [ 1.17493775e+00,  1.19618940e+00,  1.17029815e+00,
         1.26707621e+00, -3.33869890e-01],
       [-1.49875879e-01, -2.32430335e-01, -2.23579971e-01,
        -2.62352551e-01, -5.71231888e-01],
       [-1.18540858e+00, -1.20438448e+00, -1.18511302e+00,
        -1.15885311e+00,  1.66878789e-01],
       [ 9.88230382e-01,  1.03790997e+00,  1.02503026e+00,
         1.09759378e+00, -7.56366689e-01],
       [-4.32241131e-01, -3.37364354e-01, -3.59047289e-01,
        -2.69949409e-01,  3.44416805e-01],
       [-1.21506501e-02, -2.72530648e-02,  3.98621768e-02,
         2.75203195e-02, -1.52375099e-01],
       [-2.44510496e+00, -2.52396801e+00, -2.49598092e+00,
        -2.47204563e+00,  2.88505139e-01],
       [-7.97011496e-01, -8.19237900e-01, -7.82167923e-01,
        -7.46836603e-01,  2.73302512e-02],
       [-3.86579490e-02, -7.29782134e-02, -6.21712979e-02,
        -1.06311541e-01, -3.82923888e-01],
       [ 9.96297935e-01,  9.22424407e-01,  9.24149946e-01,
         9.58501460e-01, -8.51106980e-01],
       [ 1.43438384e-01,  2.28339228e-01,  1.22295380e-01,
         2.64794826e-01,  2.98892578e+00],
       [-5.91288442e-01, -5.48403295e-01, -5.42937824e-01,
        -4.89107029e-01, -7.39928292e-01],
       [ 1.20893666e+00,  1.25012160e+00,  1.26253193e+00,
         1.25480299e+00, -6.24237103e-01],
       [ 1.21527552e+00,  1.14694707e+00,  1.17260360e+00,
         1.13558164e+00, -1.51416121e+00],
       [ 3.73940918e-01,  4.76310364e-01,  4.35313030e-01,
         5.13758453e-01,  6.57163133e-01],
       [ 5.43937240e-01,  5.16759740e-01,  3.41926966e-01,
         3.40185547e-01,  2.16018719e+00],
       [-1.10530899e+00, -1.05431211e+00, -1.04157444e+00,
        -1.12904710e+00,  5.25894924e-01],
       [-2.15582404e+00, -2.12768220e+00, -2.14434063e+00,
        -2.05476956e+00,  1.19586239e+00],
       [-1.30238855e+00, -1.40545867e+00, -1.39379087e+00,
        -1.38093301e+00, -5.72982427e-01],
       [-1.25283047e+00, -1.17566024e+00, -1.18165441e+00,
        -1.12086525e+00,  1.94187200e-01],
       [-1.08917388e+00, -1.05607070e+00, -1.03523335e+00,
        -1.12203434e+00,  1.60345460e+00],
       [ 8.64911561e-01,  8.08697434e-01,  8.57857522e-01,
         8.42202387e-01,  7.80069711e-02],
       [-1.42109721e+00, -9.92758748e-01, -1.35978001e+00,
        -1.08287829e+00,  5.31567021e+00],
       [-5.65217547e-02, -8.11861630e-02, -5.75595210e-02,
        -1.98175837e-02, -4.18521685e-02],
       [ 2.12589848e-01,  2.99857339e-01,  2.76210685e-01,
         3.62392913e-01,  2.85454200e-01],
       [ 2.46012821e-01,  2.74064376e-01,  2.96963241e-01,
         2.49600219e-01, -1.52286183e-01],
       [-9.57210687e-01, -1.03027684e+00, -9.87964179e-01,
        -1.05365727e+00,  2.23623839e+00],
       [ 2.13165788e-01,  1.21646618e-01,  2.03000156e-01,
         1.24534306e-01, -1.62956136e-01],
       [ 1.34666189e+00,  1.29995073e+00,  1.37436422e+00,
         1.36876477e+00, -1.10481846e+00],
       [ 1.66489165e-01,  1.91407033e-01,  2.12799852e-01,
         1.64274460e-01, -2.18973390e-01],
       [-4.43190142e-01, -5.10885202e-01, -4.33987124e-01,
        -4.49950974e-01, -9.31126071e-01],
       [-1.42052127e+00, -1.36031942e+00, -1.38860295e+00,
        -1.28567221e+00,  6.68405485e-01],
       [ 6.49392255e-01,  7.15488546e-01,  7.12589628e-01,
         7.58629818e-01,  3.73920337e-01],
       [ 2.66758084e-01,  2.52373599e-01,  2.95810077e-01,
         2.78236244e-01, -3.73259800e-01],
       [-5.54984012e-01, -5.29644696e-01, -4.96820935e-01,
        -5.41705392e-01, -7.33887543e-01],
       [ 7.39288102e-01,  7.65903568e-01,  6.05368234e-01,
         5.23693491e-01,  3.17292134e+00],
       [-1.08974982e+00, -1.17155626e+00, -1.21047736e+00,
        -1.29502315e+00, -1.49913230e-01],
       [ 1.34839059e+00,  1.30815778e+00,  1.32421258e+00,
         1.33603738e+00, -1.64095376e-01],
       [ 4.03906494e-01,  6.20520173e-01,  4.65865282e-01,
         6.48174413e-01, -3.16809079e-01],
       [ 1.39506721e+00,  1.36971025e+00,  1.34957691e+00,
         1.27408897e+00, -3.59105440e-01],
       [ 1.23371614e+00,  1.21084492e+00,  1.14205135e+00,
         1.10519153e+00,  7.34286888e-01],
       [-2.44395221e+00, -2.54507200e+00, -2.72368202e+00,
        -2.80282730e+00,  2.96829164e+00],
       [-2.62547304e+00, -2.72855894e+00, -2.68967071e+00,
        -2.80574958e+00,  1.23693615e+00],
       [-4.32241131e-01, -4.69264028e-01, -4.43210678e-01,
        -5.41120401e-01, -5.55204729e-01],
       [-1.29547287e+00, -1.37028507e+00, -1.37246217e+00,
        -1.43353048e+00,  5.48374070e-01],
       [ 3.62555503e-02,  8.53012161e-02,  9.75080686e-02,
         1.40313013e-01, -2.15049959e-01],
       [ 1.07870305e+00,  1.07601396e+00,  1.08498248e+00,
         1.03155400e+00, -6.62798980e-01],
       [ 4.71328379e-01,  3.87790455e-01,  3.22326695e-01,
         3.01613592e-01,  9.30171499e-02],
       [ 1.23602078e+00,  1.19267222e+00,  1.25388452e+00,
         1.20103643e+00, -1.37013351e+00],
       [ 5.35425369e-02, -1.49429295e-02, -2.41247982e-02,
        -2.68303422e-02, -7.33943115e-01],
       [-9.85891002e-02, -8.73308924e-04, -3.79601289e-02,
         3.16116898e-02,  3.03491772e+00],
       [ 7.54405590e-02,  1.04646609e-01,  1.24601708e-01,
         1.58430792e-01,  1.21764893e-01],
       [ 4.25228576e-01,  4.70447798e-01,  4.39347785e-01,
         4.48887762e-01, -1.09011743e-01],
       [-9.22502454e-02, -1.11083100e-01, -5.17945800e-02,
        -6.94936675e-02, -7.53632513e-01],
       [-1.47411269e+00, -1.59011786e+00, -1.48141287e+00,
        -1.53814132e+00, -1.79783541e-01],
       [-5.90711623e-01, -5.46058806e-01, -5.48125743e-01,
        -4.75081512e-01,  5.58232662e-01],
       [ 2.70215481e-01,  2.83443229e-01,  2.53728822e-01,
         3.26159138e-01, -4.03185684e-01],
       [ 1.18934416e+00,  1.17977529e+00,  1.23947304e+00,
         1.20337372e+00, -1.19045039e+00],
       [-2.22497462e+00, -2.23144353e+00, -2.17028110e+00,
        -2.20671831e+00, -2.35798739e-02],
       [ 1.34896741e+00,  1.33453754e+00,  1.27290777e+00,
         1.26532213e+00, -6.79220705e-01],
       [ 2.28148136e-01,  2.40649363e-01,  1.94929766e-01,
         2.40833379e-01, -6.42034974e-02],
       [-1.33869210e+00, -1.34683660e+00, -1.27965225e+00,
        -1.28684130e+00, -6.96885201e-02],
       [ 2.55809073e-01,  2.47683726e-01,  2.92927607e-01,
         2.06937785e-01, -6.52412448e-01],
       [-2.43300319e+00, -2.39793001e+00, -2.39394744e+00,
        -2.50594212e+00,  6.71656486e-01],
       [ 9.44435217e-01,  9.23597099e-01,  1.01004264e+00,
         9.67852399e-01, -6.86734130e-01],
       [-1.17215405e+00, -1.24952373e+00, -1.18568917e+00,
        -1.19684007e+00,  2.44182432e-02],
       [ 1.35703496e+00,  1.31401945e+00,  1.37551738e+00,
         1.31967368e+00, -1.30760314e+00],
       [ 2.78283035e-01,  3.11582470e-01,  3.29244800e-01,
         3.53042865e-01, -3.82218115e-01],
       [ 1.19395432e+00,  1.20732774e+00,  1.20085040e+00,
         1.15252943e+00, -7.40611836e-01],
       [-4.85256608e-01, -4.70436720e-01, -4.14963874e-01,
        -4.00859881e-01, -9.60577531e-02],
       [ 1.17609051e+00,  1.40195257e+00,  1.22390841e+00,
         1.28986857e+00,  1.21162836e+00],
       [ 9.54807409e-01,  9.18907226e-01,  9.00514919e-01,
         9.10579457e-01,  6.76593396e-02],
       [ 9.92840538e-01,  9.58769809e-01,  1.00773631e+00,
         9.79540627e-01, -1.00876109e+00],
       [-1.33740772e-01, -1.72049667e-01, -3.31377507e-01,
        -3.58781547e-01,  6.62459209e-01],
       [-4.66816863e-01, -4.68677235e-01, -4.38021879e-01,
        -4.56963733e-01, -5.17837664e-01],
       [ 2.37368448e-01,  2.77581558e-01,  2.52575658e-01,
         3.48367396e-01, -9.06607408e-01],
       [-4.58172490e-01, -5.43127523e-01, -5.54466827e-01,
        -5.41705392e-01, -3.99734621e-01],
       [-1.14564675e+00, -1.22197128e+00, -1.12919644e+00,
        -1.17813908e+00, -6.39080564e-01],
       [ 7.05865130e-01,  7.93456016e-01,  7.67930071e-01,
         8.54474714e-01,  1.17213491e-01],
       [-1.63143042e+00, -1.61825620e+00, -1.58632882e+00,
        -1.58489513e+00, -3.59366632e-01],
       [ 1.09138076e+00,  1.18211978e+00,  1.14378065e+00,
         1.22382878e+00,  1.46516756e+00],
       [ 3.04214394e-01,  3.15099651e-01,  3.39620638e-01,
         3.75835222e-01, -8.35207639e-01],
       [-1.15947634e+00, -1.24366117e+00, -1.18972480e+00,
        -1.24476296e+00,  6.19834969e-01],
       [ 8.92710276e-02,  1.46854576e-01,  1.11343399e-01,
         2.11612363e-01,  1.17030452e+00],
       [ 1.22694000e-01,  5.18862028e-02,  1.39217014e-02,
        -6.24800173e-02,  3.27000330e-01],
       [-1.96552501e-01, -2.26568664e-01, -1.60169138e-01,
        -2.00988239e-01, -3.46318168e-01],
       [-1.49024780e+00, -1.58777337e+00, -1.52234184e+00,
        -1.61996070e+00, -1.79261158e-01],
       [-9.74363414e-02, -4.97728369e-03, -7.48534645e-02,
         5.49881458e-02, -9.83529045e-02],
       [-1.43377492e+00, -1.24131668e+00, -1.36727425e+00,
        -1.31839960e+00,  1.43112930e+00],
       [ 1.78149255e-02,  5.42315868e-02,  6.69558163e-02,
         1.18105647e-01,  3.77449201e-01],
       [ 6.33387891e-02,  6.65417221e-02,  7.27198777e-02,
         1.09923798e-01, -5.65552361e-01],
       [ 4.59803429e-01,  3.97756995e-01,  2.64680803e-01,
         1.95833657e-01, -2.08892507e-01],
       [-1.09435998e+00, -1.18914306e+00, -1.16954839e+00,
        -1.25235982e+00, -1.40193570e-01],
       [ 1.28788350e+00,  1.22315505e+00,  1.17779240e+00,
         1.14259440e+00, -4.62109389e-01],
       [ 8.69655098e-02,  1.55647530e-01,  1.57459409e-01,
         1.78300869e-01, -6.96437119e-01],
       [-2.69001347e+00, -2.58083150e+00, -2.68217690e+00,
        -2.53691633e+00,  1.61438574e+00],
       [ 5.72750057e-01,  6.23451456e-01,  3.81701893e-01,
         3.82847980e-01,  3.51451544e+00],
       [-8.85754585e-01, -8.74342796e-01, -8.57684780e-01,
        -8.03525446e-01,  8.46571472e-01],
       [ 1.10693905e+00,  1.17274093e+00,  1.17548607e+00,
         1.22499787e+00, -4.54834926e-01],
       [ 9.84772984e-01,  9.82805075e-01,  1.03655926e+00,
         1.01519030e+00, -1.12753101e+00],
       [ 3.11706008e-01,  3.16858242e-01,  3.76513974e-01,
         3.13301820e-01, -8.33962811e-01],
       [ 1.00955246e+00,  1.17742991e+00,  1.08152298e+00,
         1.19168549e+00,  4.40340795e-01],
       [-1.23900000e+00, -1.23486821e+00, -1.23930030e+00,
        -1.17112543e+00,  1.02604897e+00],
       [ 4.26380456e-01,  3.67859163e-01,  4.11101861e-01,
         4.18497656e-01, -8.27144044e-01],
       [-2.42076365e-01, -2.61741374e-01, -2.03979699e-01,
        -1.95728670e-01, -1.94254665e-01],
       [-1.37269189e+00, -1.42832125e+00, -1.39840265e+00,
        -1.40956903e+00, -4.27543186e-01],
       [-3.33124971e-01, -3.13914987e-01, -2.64508061e-01,
        -2.81053538e-01, -1.14261304e-02],
       [-2.23649957e+00, -2.34810178e+00, -2.30459614e+00,
        -2.31542053e+00,  7.04377676e-01],
       [ 3.26112416e-01,  3.47341973e-01,  3.67290420e-01,
         3.01028601e-01,  3.80483469e-01],
       [ 4.94379160e-01,  5.61312197e-01,  5.50604813e-01,
         6.28888435e-01, -2.46176213e-01],
       [ 2.70352379e-02, -6.47711584e-02,  2.96884127e-03,
        -5.60513581e-02, -1.19136734e+00],
       [-1.83874792e-01, -1.99016216e-01, -2.45484812e-01,
        -3.26054152e-01,  3.57404139e-01],
       [ 1.07870305e+00,  1.00859893e+00,  1.05615953e+00,
         1.02921671e+00, -1.14314137e+00],
       [ 1.04931341e+00,  1.04201305e+00,  1.01177195e+00,
         9.54995081e-01, -8.71963404e-01],
       [ 6.67970657e-02,  1.61266999e-02,  4.33207896e-02,
         4.21308275e-02, -5.10713248e-01],
       [-2.34310735e+00, -2.30941100e+00, -2.29191397e+00,
        -2.23652432e+00, -4.97379307e-02],
       [-1.99216745e+00, -1.81698501e+00, -1.93220417e+00,
        -1.86541706e+00,  1.28126092e+00],
       [-7.67622740e-01, -7.77615832e-01, -6.95699086e-01,
        -7.16446497e-01, -4.11182592e-01],
       [ 5.91766622e-01,  5.74795024e-01,  5.99027151e-01,
         5.48239038e-01, -2.74596078e-01],
       [ 1.02626351e+00,  9.89253539e-01,  1.05846498e+00,
         1.02337215e+00, -9.64875355e-01],
       [-1.70173377e+00, -1.58777337e+00, -1.63359799e+00,
        -1.58372693e+00,  6.58596908e-01],
       [ 8.72979115e-01,  8.67905410e-01,  9.25879252e-01,
         8.67332033e-01,  1.16135382e-01],
       [-3.79801594e-01, -4.04779385e-01, -3.32530671e-01,
        -3.83327094e-01, -4.88022926e-01],
       [ 9.72672094e-01,  9.75770712e-01,  9.93324840e-01,
         9.74866049e-01, -2.38507184e-01],
       [ 1.19049692e+00,  1.17332683e+00,  1.21065010e+00,
         1.20980238e+00, -5.75227563e-01],
       [-4.67255025e-02, -7.35650067e-02, -4.43012122e-02,
        -1.12740200e-01, -8.60102140e-02],
       [ 1.01646726e+00,  1.01094342e+00,  1.02675956e+00,
         1.06428229e+00, -7.23856675e-01],
       [-3.50988777e-01, -4.38194398e-01, -3.63659066e-01,
        -4.32418186e-01, -6.90568644e-01],
       [-7.71656077e-01, -7.13717982e-01, -7.84474252e-01,
        -8.88266214e-01,  9.44573880e-01],
       [ 3.31298512e-01,  4.04205459e-01,  3.40197660e-01,
         2.79990325e-01,  1.80049512e-01],
       [-1.18310306e+00, -1.04669095e+00, -1.14014930e+00,
        -1.00398119e+00,  9.70098408e-01],
       [ 1.45960852e+00,  1.48343722e+00,  1.42624605e+00,
         1.46577876e+00,  4.51633162e-01],
       [ 2.20080582e-01,  1.74992923e-01,  1.47659713e-01,
         6.90145545e-02,  1.42061495e+00],
       [-1.92518285e-01, -2.00188908e-01, -2.02827415e-01,
        -1.32026178e-01, -7.70165383e-01],
       [-9.22502454e-02, -6.14908119e-03, -2.58541046e-02,
         3.68712586e-02, -3.15897688e-01],
       [ 1.20547927e+00,  1.14753297e+00,  1.23428512e+00,
         1.17006222e+00, -1.65525466e+00],
       [-2.11534849e-01, -1.84360697e-01, -1.46910829e-01,
        -1.60078995e-01, -4.20891137e-01],
       [ 1.01185710e+00,  9.41769800e-01,  9.88713943e-01,
         9.73696959e-01, -4.32466925e-01],
       [ 9.05249329e-01,  8.52078093e-01,  5.79427759e-01,
         5.77460054e-01,  1.28101084e+00],
       [-8.48298275e-01, -9.27688207e-01, -8.89966339e-01,
        -8.98786243e-01, -7.06467986e-01],
       [-1.23381390e+00, -1.22607526e+00, -1.22892358e+00,
        -1.19450278e+00,  8.33100656e-01],
       [ 1.89676844e-02, -1.67015202e-02,  2.77561525e-02,
         3.10266987e-02, -2.76763412e-01],
       [-1.37096319e+00, -1.35621634e+00, -1.34018061e+00,
        -1.29794454e+00,  3.31403702e+00],
       [-7.34775707e-01, -7.94029942e-01, -7.81015639e-01,
        -8.61967478e-01, -3.50908471e-01],
       [ 2.06963831e-02, -3.78055038e-02,  1.81567715e-03,
         2.40139402e-02, -8.27371892e-01],
       [ 3.35908668e-01,  4.24136751e-01,  3.98419694e-01,
         4.72848317e-01, -3.32430558e-01],
       [ 1.35242481e+00,  1.32691638e+00,  1.41068141e+00,
         1.39740169e+00, -9.99786108e-01],
       [-8.47586316e-02, -8.73308924e-04, -2.81604329e-02,
         4.21308275e-02, -3.63456781e-01],
       [ 6.39156082e-02,  2.15442299e-01,  1.01542824e-01,
         2.60704348e-01, -8.22812877e-02],
       [ 9.49045373e-01,  8.78457849e-01,  8.75151465e-01,
         8.79605252e-01, -6.70573597e-01],
       [-1.43953696e+00, -1.47404640e+00, -1.38168573e+00,
        -1.46742696e+00, -7.61690551e-01],
       [-2.25228420e-02,  4.60245317e-02,  3.12156449e-02,
         8.53782521e-02,  1.33901965e-01],
       [ 1.23947818e+00,  1.27063969e+00,  1.28270746e+00,
         1.32551824e+00, -2.96058244e-01],
       [-2.63930307e+00, -2.67638488e+00, -2.67122404e+00,
        -2.72743703e+00,  1.68990345e+00],
       [-1.01541226e+00, -9.66964891e-01, -9.95458427e-01,
        -9.13396751e-01,  8.30071946e-01],
       [ 4.03330554e-01,  3.49100564e-01,  3.55185275e-01,
         3.95705299e-01,  5.06727909e-01],
       [ 9.79010069e-01,  1.01915048e+00,  9.82949002e-01,
         9.78372428e-01,  1.13673512e-01],
       [ 3.91228784e-01,  3.77238910e-01,  3.56338439e-01,
         2.88756273e-01, -2.23280272e-01],
       [ 2.88655227e-01,  3.40306715e-01,  3.17714918e-01,
         4.12653096e-01,  5.66679708e-01],
       [-1.61839872e-02, -2.43226765e-02,  1.56510078e-02,
        -2.28479577e-03, -1.47067909e-01],
       [ 7.03559612e-01,  6.50418005e-01,  6.43990876e-01,
         6.38824366e-01, -5.10657675e-01],
       [ 2.06963831e-02, -4.54266601e-02,  1.04630887e-02,
        -7.35841460e-02, -7.43440485e-01],
       [-1.02622437e-01, -1.78742122e-02, -8.58063246e-02,
        -1.70069648e-03, -1.51413692e-01],
       [-3.80378413e-01, -3.77813731e-01, -3.37718590e-01,
        -3.72807956e-01, -3.47235118e-01],
       [ 5.56614950e-01,  5.35518340e-01,  5.86344985e-01,
         5.76290963e-01, -5.20405122e-01],
       [ 1.63031768e-01,  2.03131269e-01,  2.32976266e-01,
         2.65379817e-01,  1.03532405e+00],
       [ 8.78165211e-01,  9.13630559e-01,  9.32797357e-01,
         9.47982322e-01, -4.16123002e-01],
       [ 1.22219031e+00,  1.17742991e+00,  1.17087429e+00,
         1.13967212e+00, -8.93381112e-01],
       [-1.65505714e+00, -1.62411877e+00, -1.73505444e+00,
        -1.61294794e+00,  1.05359635e+00],
       [-2.48283598e-02, -4.01499933e-02, -3.45006365e-02,
        -3.67662723e-02, -5.06272991e-01],
       [-4.38004046e-01, -5.23196232e-01, -4.25916734e-01,
        -4.55795534e-01, -9.55211267e-01],
       [ 4.19465661e-01,  3.40306715e-01,  3.46537864e-01,
         3.61224714e-01,  3.41421438e-01],

In [10]:
display(X_train.mean()) # the value below, 3.5*e^(-16) comes close to 0 only!!!
display(X_train.max())
display(X_train.min())

3.5704772471945036e-16

5.31567020856729

-2.8057495836789856

In [11]:
X_test=sc.transform(X_test) #no need to do fit_transform again. Only transform will do, bcz already fit once with X_train.
X_test

array([[ 1.2665623 ,  1.30815778,  1.3098011 ,  1.332531  , -0.5786953 ],
       [-2.38805527, -2.39206834, -2.36108886, -2.31074506,  0.59763924],
       [ 0.02530654, -0.05480551, -0.00798402, -0.08585737, -0.44221437],
       [-0.64315116, -0.69437259, -0.58501908, -0.62352388, -0.51143569],
       [ 0.61539246,  0.59062324,  0.61113318,  0.63823937, -0.06901053],
       [ 0.11404963,  0.16209599,  0.15169535,  0.10291015, -0.10999538],
       [ 0.23391105,  0.27934015,  0.29350375,  0.3325878 , -0.34386741],
       [-0.0040831 , -0.0747377 , -0.13653411, -0.15189715,  0.45664582],
       [-2.1817554 , -2.17047696, -2.14952855, -2.16756226,  0.2746342 ],
       [ 0.48054869,  0.43761958,  0.45202995,  0.46291328,  0.18012176],
       [ 0.19299646,  0.20664845,  0.21741163,  0.14206709,  0.03324318],
       [ 0.64996819,  0.71841983,  0.69817816,  0.78142217,  0.41283232],
       [ 1.17666645,  1.1240845 ,  1.15300421,  1.17765908,  0.12442682],
       [ 1.43137164,  1.41191822,  1.47466839,  1.43422046,  3.86519012],
       [-0.59589772, -0.70082105, -0.62883052, -0.71469331, -0.61466193],
       [ 1.0833132 ,  1.09125538,  1.11899334,  1.06837277, -1.06071599],
       [ 0.31746804,  0.3244794 ,  0.35633844,  0.3957053 , -0.61983575],
       [-1.8325442 , -1.86915952, -1.8797462 , -1.82158553,  0.39426549],
       [ 0.21835188,  0.29692695,  0.27390436,  0.28875627,  0.47530712],
       [-1.27069427, -1.11879675, -1.19779519, -1.07411234,  1.3680821 ],
       [ 1.14093884,  1.12467039,  1.13398096,  1.17590589, -0.59001545],
       [-1.72824194, -1.75719114, -1.67971488, -1.67957182,  0.39844456],
       [ 0.80901463,  0.74304099,  0.74083643,  0.69492822,  2.36355538],
       [-0.66101497, -0.71840786, -0.67091177, -0.75560255, -0.47634711],
       [ 0.21835188,  0.12809508,  0.13843704,  0.11576747,  2.80644179],
       [-1.10242753, -1.15924613, -1.22143022, -1.31138685, -0.27070043],
       [-0.79874019, -0.74830479, -0.7919685 , -0.82398051,  0.49556336],
       [-2.06708007, -2.09309539, -2.0976476 , -2.21022469,  0.60952624],
       [-1.12835889, -1.10296854, -1.06866808, -1.03437129,  0.38173385],
       [ 0.76060931,  0.82511154,  0.82154033,  0.87843616, -0.44313132],
       [ 0.15093   ,  0.06478313,  0.07041443, -0.00871345,  0.30479349],
       [-1.29604969, -1.34918108, -1.32634528, -1.43469957,  0.00903017],
       [ 1.34435725,  1.3415719 ,  1.21814435,  1.17999726, -0.6248873 ],
       [ 0.87355593,  0.89018209,  0.9431732 ,  0.87551388, -0.27309562],
       [-1.0839869 , -1.15690074, -1.16724294, -1.23365884,  0.30094786],
       [ 0.58254631,  0.57655361,  0.63534434,  0.60083651, -0.20982057],
       [-1.59800745, -1.68625803, -1.6468563 , -1.75496165,  0.29512384],
       [ 0.50302265,  0.44641253,  0.38746683,  0.34018555, -0.40443607],
       [ 0.10713483,  0.11637085,  0.14074249,  0.05264997,  0.24136284],
       [ 0.25177486,  0.1972687 ,  0.27851613,  0.24550885, -0.92364599],
       [ 0.7410168 ,  0.77645511,  0.78349383,  0.79778587, -0.3126189 ],
       [ 0.0742878 ,  0.02316196,  0.11710746,  0.06842956, -0.8410261 ],
       [ 0.30018018,  0.38251468,  0.34826805,  0.44070591, -0.47180126],
       [-0.1930951 , -0.13394567, -0.21896819, -0.13670165, -0.1339472 ],
       [ 0.99111184,  1.03146151,  1.06422992,  1.07655461, -0.67796476],
       [-1.70115783, -1.76246691, -1.7016206 , -1.69885691, -0.25561245],
       [ 1.08792336,  1.05842716,  1.11092295,  1.06019092,  0.14062626],
       [-0.63738825, -0.49916097, -0.57637255, -0.43650956,  0.54132745],
       [ 0.3918056 ,  0.34089351,  0.19608293,  0.19115819,  1.75973607],
       [-1.47757009, -1.47932217, -1.4174259 , -1.49723208, -0.45334558]])

In [12]:
display(X_test.mean()) # the value below, for mean comes close to 0 only!!!
display(X_test.max())    #again we can see, how mean comes almost middle to max and min.
display(X_test.min())

-0.07658818680765117

3.8651901170790075

-2.3920683392597395

In [13]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(X_train,Y_train)  #we need to fit X and Y

LinearRegression()

In [14]:
lr.intercept_   #value of c , i.e. y-intercept

172.60289836883544

In [15]:
lr.coef_       #value of m or slope. Note we got 5 values, since there were 5 columns. One value for each column

array([ 0.46772418,  0.09382266, -0.88850751, 17.58784584, -0.04000523])

In [16]:
Y_pred=lr.predict(X_test)
Y_pred

array([195.61376753, 132.69442563, 171.1243315 , 161.8107452 ,
       183.63116624, 174.35103617, 178.34099178, 170.02547628,
       135.15493333, 180.60153081, 175.01670818, 186.08098902,
       192.94177404, 197.16482194, 160.27182432, 191.05055032,
       179.44962045, 141.18703398, 177.54910528, 154.0217928 ,
       192.93976724, 143.56614256, 184.5205052 , 159.55206808,
       174.51787071, 150.01011248, 158.35090291, 134.40599555,
       154.7135396 , 187.7736505 , 172.45156212, 147.81495248,
       193.05383487, 187.66631282, 151.31501118, 182.94076877,
       142.2827051 , 178.53510116, 173.45521908, 176.84662661,
       186.3700401 , 173.77294088, 180.23969184, 170.29564195,
       191.17906225, 143.28476145, 190.86483611, 165.07113649,
       175.93557979, 146.71745193])

In [17]:
Y_test[7]

C:\Users\LUCIFER\AppData\Local\Temp\ipykernel_1468\3744045608.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  Y_test[7]

170.20574951171875

In [18]:
Y_pred[7]

170.02547628250244

In [19]:
Y_test[7]-Y_pred[7]

C:\Users\LUCIFER\AppData\Local\Temp\ipykernel_1468\2864400473.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  Y_test[7]-Y_pred[7]

0.1802732292163114

In [20]:
Y_test[10]-Y_pred[10]

C:\Users\LUCIFER\AppData\Local\Temp\ipykernel_1468\4000055854.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  Y_test[10]-Y_pred[10]

0.2124483161692865

In [21]:
Y_test[20]-Y_pred[20]

C:\Users\LUCIFER\AppData\Local\Temp\ipykernel_1468\1632016826.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  Y_test[20]-Y_pred[20]

0.21022665952156672

In [22]:
lr.score(X_test,Y_pred)

1.0

In [23]:
from sklearn.metrics import mean_absolute_error, mean_squared_error
mse=mean_squared_error(Y_test,Y_pred)
mse

0.034734198159911515

In [24]:
mae=mean_absolute_error(Y_test,Y_pred)
mae

0.16182034151523225